services:
 ordering.db:
    image: mcr.microsoft.com/mssql/server
    container_name: ordering.db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123
    restart: always
    ports:
      - "1433:1433"